CREATE TABLE `GROUP_PAGE_CONTENT` (
      `PAGE_CONTENT_ID` bigint(20) NOT NULL,
      `GROUP_ID` bigint(20) NOT NULL,
      KEY `FKC122C0899E07AF79` (`GROUP_ID`),
      KEY `FKC122C089BC9FC1A` (`PAGE_CONTENT_ID`),
      CONSTRAINT `FKC122C089BC9FC1A` FOREIGN KEY (`PAGE_CONTENT_ID`) REFERENCES `PageContent` (`pageContentId`),
      CONSTRAINT `FKC122C0899E07AF79` FOREIGN KEY (`GROUP_ID`) REFERENCES `GROUP_DETAILS` (`groupId`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

